# Generated by Django 5.2.6 on 2025-10-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notre_livre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_bibliothecaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='mot_de_passe',
            field=models.CharField(default='temp123', max_length=128),
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
