# Generated by Django 5.2.6 on 2025-10-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notre_livre', '0002_emprunt_rendu_membre_est_bibliothecaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='notre_livre.media'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='notre_livre.membre'),
        ),
    ]
