# Generated by Django 5.2.6 on 2025-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notre_livre', '0003_alter_emprunt_media_alter_emprunt_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='mot_de_passe',
            field=models.CharField(max_length=128),
        ),
    ]
